### ISSUE TITLE
Get list of cities by country

### ISSUE THREAD

**Issue by trantorLiu** [yhirose/maxminddb#49]
Hello, is there any way to get all cities (subdivisions) by country code? Thanks!

**Comment by yhirose** [comment]
@trantorLiu, thanks for the question. Unfortunately, this gem doesn't support such a feature.

As you can see [the MaxMind DB 2.0 file format spec](https://maxmind.github.io/MaxMind-DB/), this DB is optimized for pinpoint IP lookup. In order to do your request, we need to enumerate all the items in the binary DB file and filter out only necessary items. But it's an extremely slow to extract all the items from the DB, because items are compressed in complex binary format.

I actually did an experiment. I added the following method in MaxMindDB class.

```rb
    def enum_items
      epos = @data.rindex(METADATA_BEGIN_MARKER)
      off = 0
      while @data_section_start + off < epos
        off, val = decode(off, @data_section_start)
        yield val
      end
    end
```

And measure time with the following test code.

```rb
cities_in_italy = []
db.enum_items do |item|
  if item.country.iso_code == 'IT'
    cities_in_italy.push item.city.name
  end
end
```

This test took 1 minute 43 seconds on my MacBook. It's really slow, right? So it doesn't look practical to do such a job with the MaxMindDB binary format. I would rather download the CSV version of MaxMindDB and simply grep on the file. Hope it helps.

**Comment by trantorLiu** [comment]
Hello @yhirose Thank you for the reply. I'll try parsing CSV instead. If there's any progress, I'll share it here.
