### ISSUE TITLE
UTF-8 corrupted values for country.iso_code

### ISSUE THREAD

**Issue by owentran** [yhirose/maxminddb#53]
Hi.

We use maxminddb (0.1.19) and we're seeing the occasional issue where the country.iso_code that is returned is corrupted.

```
maxminddb.lookup('220.255.100.153')
"SG #\xE8BdeHSingapurBe"
```

```
maxminddb.lookup('83.10.231.26')
"\xB8\xE3"
```

We can never reproduce the issue, but we get an exception notification when the garbled UTF-8 is returned and we try to insert an invalid country.iso_code.

I was wondering it could be an issue with https://github.com/yhirose/maxminddb/pull/38?

My plan is to:

1. Upgrade to v0.1.22
2. Add a rescue to attempt to do another lookup if it detects invalid UTF-8 encoding

Note: we have an initializer to load one shared instance across the app.

Any other suggestions?

Thanks!
Owen

**Comment by yhirose** [comment]
@owentran, thanks for the report. As you see the thread at #44, the version 0.1.19 (#38) has a serious problem. So it would be safter to use the latest version and I hope it fixes the problem.
If it still happens even with the latest version, I would like to look into it seriously, because it could happen with any other field as well. Please let me know the outcome with the latest on your environment. Thanks for your help!

**Comment by owentran** [comment]
@yhirose thanks for point out #44 to me. I totally missed it. I'll go ahead and close this out for now. I'll be upgrading the gem for our release next week and will re-open if I see any other issues. BTW, the occurrence is really low, we've only seen it happen 4 times since May, but just recently saw it twice in the past week.
